name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.13.4
          otp-version: 24.3.3
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install Mix dependencies
        run: mix deps.get
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Run tests
        run: mix test
env:
  MIX_ENV: test
